# Site settings
baseurl: "./"

# Build settings
markdown: kramdown
kramdown:
  toc_levels: "1,2,3"
  input: GFM
  syntax_highlighter: rouge
exclude: ['*/Makefile']

# Defaults
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
